### ISSUE TITLE
add a surround choosing the inner most delimited text

### ISSUE THREAD

**Issue by amosbird** [cute-jumper/embrace.el#15]
Hi, is it possible to surround the inner most `[{('"` by a key using embrace? This is applicable using expand-region though.

**Comment by cute-jumper** [comment]
What operation do you want? If you just want "adding" (not deleting/changing), I'll suggest you to use `expand-region` to select the region first and then add a pair to surround the current region.

**Comment by amosbird** [comment]
ah, I have fouund `evil-textobj-anyblock` for achieving this. Thanks!
