### ISSUE TITLE
disable popup help window

### ISSUE THREAD

**Issue by amosbird** [cute-jumper/embrace.el#16]
Is there a way to get rid of the help window? it often breaks current terminal frame's rendering.

**Comment by cute-jumper** [comment]
Set `embrace-show-help-p` to `nil`. Actually, it is in the README: https://github.com/cute-jumper/embrace.el#disable-help-message

**Comment by amosbird** [comment]
well, it still shows the help window after `embrace-show-help-p` is set to `nil`,

![](https://la.wentropy.com/4uop.png)

**Comment by cute-jumper** [comment]
So you're using `evil-embrace`, right? Then you should use `(setq evil-embrace-show-help-p nil)` instead. See the README here: https://github.com/cute-jumper/evil-embrace.el#usage

**Comment by amosbird** [comment]
Thanks!
