### ISSUE TITLE
Cannot mark region (C-SPC) after embrace-delete or embrace-change

### ISSUE THREAD

**Issue by fmdkdd** [cute-jumper/embrace.el#17]
In `emacs -Q`, after `package-initialize`:

Type `"foo"`, put the cursor inside: `"f|oo"`, then `M-x embrace-delete "`.  The quotes are deleted, but the word is marked, then the region disappears by itself in one or two seconds.  After that, `C-SPC` does not begin marking, but hitting `C-SPC` a second time does.

Same thing happens with `embrace-change`, but not `embrace-add`.

(Very nice package, BTW!)

**Comment by fmdkdd** [comment]
Actually, it looks like the issue lies with `expand-region` itself: magnars/expand-region.el/issues/229.

Sorry for the noise!

**Comment by cute-jumper** [comment]
I was just about to look into this issue. Thank you for your update! Hope it could be fixed in the upstream soon.
