### ISSUE TITLE
Using embrace in elisp

### ISSUE THREAD

**Issue by ghost** [cute-jumper/embrace.el#18]
Is it possible to call, say, embrace-change with input given programatically rather than from the keyboard?

I have defined a custom pair (actually a regexp-pair, if it matters) bound to the key s. I would like to define a separate command that calls embrace-change and selects this pair automatically to be deleted, and which also specifies beforehand the pair to be inserted in place of it.

Is there any way to do this?

**Comment by cute-jumper** [comment]
Sure. You can make a command similar to the following code of `embrace--change-internal`:

```elisp
(defun embrace--change-internal (change-p)
  (let* ((char (read-char "Delete pair: "))
         (overlay (embrace--delete char change-p)))
    (and change-p
         (overlayp overlay)
(embrace--insert (read-char "Insert pair: ") overlay))))
```

Basically what you need to do is replacing those `read-char` with the your preselected characters, assuming you've added the pair using `embrace-add-pair-regexp`.

**Comment by ghost** [comment]
@cute-jumper That was more or less what I pieced together on my own after I asked the question. Thanks for answering and thanks for developing the package, your work is much appreciated!

**Comment by cute-jumper** [comment]
You're welcome! Glad it works!
