### ISSUE TITLE
Use `' pair in emacs-lisp-mode?

### ISSUE THREAD

**Issue by casouri** [cute-jumper/embrace.el#19]
Most of the time when I use ``` ` ``` in emacs lisp I use it for ``` ` ' ``` pair. It would be convenient if it is the default setting.

**Comment by cute-jumper** [comment]
Hmm...It seems this is undocumented, but `embrace-emacs-lisp-mode-hook` does exist and you should be able to use that directly.

**Comment by casouri** [comment]
Thanks.
