### ISSUE TITLE
MELPA

### ISSUE THREAD

**Issue by jabranham** [cute-jumper/embrace.el#3]
Would be nice to see this available via MELPA.

**Comment by cute-jumper** [comment]
Sure! The [pull request](https://github.com/melpa/melpa/pull/3798) is pending right now. Hope it can be merged soon.

**Comment by jabranham** [comment]
Awesome to hear. Wish there were some way to auto-notify me when this happens...

**Comment by cute-jumper** [comment]
Typically it would happen in just one or two days. I can ping you here when this happens :)

**Comment by cute-jumper** [comment]
@jabranham The PR has been merged. It should appear soon in melpa :)

**Comment by jabranham** [comment]
Nice! Thanks. :-)
