### ISSUE TITLE
more informative prompts

### ISSUE THREAD

**Issue by vapniks** [cute-jumper/embrace.el#4]
This is one of those emacs commands that I might spend a bit of time learning the keybindings, use them a few times, forget them, and then some time in the future (when I really need it) have to relearn them again. 
It would be nice if the prompts gave you more information about what the different keys do, both the prompt for operation type and the prompt for pair (multi-line prompts are possible).

**Comment by cute-jumper** [comment]
Thank you. Yeah. I would also like to have this. So it is actually on my TODO list! Let's see when I can have some time to get this done.

**Comment by cute-jumper** [comment]
@vapniks The help message can now be shown in a popup. Check out the latest version and let me know if there are any problems! Thanks!

**Comment by vapniks** [comment]
wow, that works great! thanks

**Comment by cute-jumper** [comment]
Closing this since it seems to work well so far.
