### ISSUE TITLE
expandable region

### ISSUE THREAD

**Issue by vapniks** [cute-jumper/embrace.el#5]
Would it be possible to add another option when prompting for the region that allows the user to toggle through different region selections (like `expand-region`).

**Comment by cute-jumper** [comment]
Sure. It should be relatively simple to be added to the package. I would possibly get this done in a few days. Thanks for the suggestion.

**Comment by vapniks** [comment]
Would also be nice if you could choose how many words/sentences/etc. to select, either by repeated presses of the selection key, or with a prefix key: positive number for forward selection and negative number for backwards selection.

**Comment by cute-jumper** [comment]
Yes. This might be useful too. I'm adding it to my TODO list. Thank you for your suggestion!

**Comment by cute-jumper** [comment]
After a second thought, I think implementing this feature is kind of redundant. If you only want to add pairs to some simple semantic units, e.g. words, symbols etc., our current method is enough. If you want to add pairs to an arbitrary region, which might not be semantically meaningful, you can always select a region first (either by `expand-region` or using `set-mark-command`, `M-3 M-f` etc.), then call `embrace-add`. Adding another way to quickly select the (possibly) arbitrary region is reinventing the wheels in some sense. If you think this is a little confusion, when adding a pair to a region, you can always select the region first.  Adding simple pairs like `()` and `[]`, you can also use `electric-pair-mode` or `smartparens-mode`, they're easier to use. 

So I think what makes this package different is that it is able to add/change/delete complicated user-defined pairs. Quickly selecting the region could be achieved outside this package so adding this feature to this package sounds redundant to me. 

What do you think?

**Comment by vapniks** [comment]
Yes, I guess that makes more sense. Will look into extending `expand-region'

**Comment by cute-jumper** [comment]
I'm closing this now. Feel free to reopen it if necessary.
