### ISSUE TITLE
Make <> consistent with other pairs

### ISSUE THREAD

**Issue by articuluxe** [cute-jumper/embrace.el#8]
For a long while I thought it was a bug that when choosing to add a pair and typing `<`, the semantic unit is surrounded with `<` and `<` rather than `<` and `>`.  It turns out `<` is treated like any character, and doubled at either end.

Why not make <> consistent with other brace pairs, such that:

typing `<` surrounds the semantic unit with `<` and `>`

whereas typing `>` surrounds the semantic unit with `<` and `>` (the latter are padded with a space on the "inside").

**Comment by cute-jumper** [comment]
Thanks for reporting this issue! It should be fixed now. :-)

**Comment by articuluxe** [comment]
Looks good, thank you!
